apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gerrit
resources:
  - repository.yaml
  - release.yaml
  - rbac.yaml
  - cert.yaml
  - ha_rbac.yaml
  - gerrit_cluster.yaml
  - ingress.yaml
  - zookeeper.yaml
