apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookwyrm
resources:
  - secret.yaml
  - keydb.yaml
  - deployment.yaml
configMapGenerator:
  - name: bookwyrm-script
    namespace: mailserver
    files:
      - bookwyrm.sh=bookwyrm.sh
    options:
      labels:
        app: bookwyrm
  - name: nginx
    namespace: bookwyrm
    files:
      - locations=nginx/locations
      - reverse_proxy.conf=nginx/reverse_proxy.conf
      - server_config=nginx/server_config
      - server_name=nginx/server_name
    options:
      labels:
        app: bookwyrm
