apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookwyrm
resources:
    - secret.yaml
    - keydb.yaml
    #- deployment.yaml
configMapGenerator:
    - name: bookwyrm-script
      namespace: mailserver
      files:
          - bookwyrm.sh=bookwyrm.sh
      options:
          labels:
              app: bookwyrm
