apiVersion: v1
kind: Secret
metadata:
  name: meowlnir
  namespace: matrix
type: Opaque
stringData:
  appservice.yaml: ENC[AES256_GCM,data:JZvYES2/qSxZNBwAmHe/454M1cEFKEaCsFrICwnr4rPl1VhtjAV/p0P24B63RnN8WsDAEoIFJohV09caelt99r+8IAm/YKlCCCha2F/Oe3kj8+1n8UyweCTB0GB9Jo+hgMJF6hwMu3tfpDMjsnBOTuauhHAWZ66U8nL3vAPp5Vk4wpmtjAVHwhCRmD+mnrYgTmjeMRV5pQhfYUA5tcMpXio6d4sNzSP8blKGHHxXUbY+L+2l8nK1qi/ZHksohOj7li5KZ83rCLvJlwETCgcYc32YECx2a7M6aBYJ/TAj+HT989ZIk+H2E6ugJyBjhNRw2Kwd8YX13BMlkLuq9+z2lXcd3SB6vjMw3zAxLlMIWC3y9rpglPJXf/Rx9XRyi1nd2LRwrbj9ilIqmCcDDe5irW+oChSd6ggvLUfMBDNaSRpgJ5HPJA5/Be9FFroNjgqUNk1K2WwL04sTunjMY2I2zMDI583gBHMm4HxG+UZig6KZbLMRdloNROuTccLHziQ/9JBTbzZhaKlmZ7jS8XU6uVTCO5azFTLyjjk/Ec6Q/Rjg7/p//MGAQbJun3fEzP5QmRGb80khnpxzkXKgf8yKJowIQhqlazF3kRtndKHgZ7rDMx6/ijvkbAec42W8eVoopQDgLQGufRqoCFWzpO7fW/yaZ7CKI0S7uedviOJD1p7lMx9CdGAW+z1tfRz3T5ljQDowdK6n9AxQsA+CQ8ckUXhTp7xkNz8g0CC+b64cMjxGHKJ6tnlz/K7rO0GXbILZXHL8IdwwCbDKousidYZUIKCLnlwnjE9L0QdnKJDXOSk9k+YwL79tk6rD7XZG3HJ5K7tZ2eYCncw7rr/SGk6BYG5zvLcXPd0k9s1sbHI2ZGwNfY/5ytirxxu/ePMWNwN5XEt4MAUKe5bvUGl+fMcCtgHDH7w+yQznQ0P8+g2gIV83A4yCJa0OyVbZ1EGYa82LG0lYIItcFTkjdvdNYsUaEnZms05Tsa9RXcv8mXMDwhlewV4IDwudukGQjp5a7eaNsErjWSDYd0hTHThWXi341l1/RSkggVq8g5DzY8hj6bEUFRH68PK36xvfZVvI4a3gPHPmFl0FzSPPUR1+2VcvlqIbmf3p6VKmQEwFpIHJoW1WDjzlQK7kHzShfnWGPKVHvo/tEiVX3oSdVvnPclg1dHUXS+fwDKCICgPpboi82EdmPwyCTvf4Hg4rM05RsWf1ep5dzx3eWt3+j+PpK/N80exSAioFGJrFBivQNUT6rRlV8EkIHLk5atKGXLXtfYf5nUMSGIvp9ZtGt8L1TPTXaF1J3/RhTGg6IZlu0cllwBq5VQsxh1mXhsHlPWKLnlnEjhwmFB2DMNy/twUmH/8lISRDRyLJNZZO2j68tGWe8atTSNw23aF9GAq52DOOdnHnI10FueONHflpF88duMCYDRdZMMcB05gOQTQg8JQzgqvmrF+SAjcp8NlYq8qOp9bthlpb816ull0Zy8fw1G7BEXXpXzMeQP+lJKsAudx+4cWVG4tHCvg350H+2oLcJ5qHkUHLHPl2,iv:k4Dq+BH8T9TlRfRJoqOp2CL1+nIJV+0zf19FNyXMuCY=,tag:XXxMTLARBfm3bwXGQdwnnQ==,type:str]
  config.yaml: ENC[AES256_GCM,data:gKvCSUpaFeoogzyHGTwGFnAf24jSkH9PIYEBQKe2dwfULrilULcnNNqW5RPb6VMjCit5QV+y/zpZwc5qdte68sIZwqblw0ROvBN5WnNpikEoyGhrgE44ede1xIMOm6vzt9o24rdTpMN00Fhc5uJTKrQk+L37vZgklw1P8E5useHUYe29JpNEhRuG3w57zh48sCiV6jAyfvWcjCGU02wzhZB2EmB2N5iVy3nnHqO6cpzQGwW3kfr7h+ay5icMR95z9Y4gdZc2twwwO6KbeRpHLg/OViOSdLqg4XLMiPxXAYlkRg4e+yt8B5Fn0cjHe2+tQQ4XRftSX4zd35f0D8xPKVibwN6Lv1gGoSd0T3FKnaI4rGyl15JekuUCjK+cqzsLaEg0XK5W4RSSjMzuPgiFa3AUs2sTO0hpWYXR6dUV5VlEjVOVrUC+OxvLAl+CD2rBAXokGo0+9vWTD/sOZTxxpupGx3GS5tzX+BBjGKOsI50TRhV/v3NlIISpdD86CF4lYw/aDA9/UM+okTP3PP7okki9RuIQC5h+w9T/ojkYHl9q/NizNtxkv5YsFTOD57EuaSEJQWzKoML21dz8MArJPXm2imFgC1CiMW35X3xLFm8KkHe8ERRkVH83sGdkblJWMHAfXiDwA0xHKTk8s4iZpCZrv6xIJG4yk0PVCtLOsY9g1QHzPTuVK3pY5/FkBZ20kflx2IIQomFSfHi4RBWJWpD0r/DZphAIyvMhwWzpnawxZTa32ZWEoDqnzraDBsTd45DxToOlwmkppoL7qJ1Ul6bW7Tqxux3JOT/YXoGms+F7QPuz3goEO+1H9im/HSevEHV5XldQ6gd6MaLvxqintqY1PZRgP7vU0HjH9AMMQYPkZ3ZIeFKXeFwmU82OyutdBFH6nqdbkQlaBKLLHyykJq+zyfmNwQfZb7EqF2xGVoxtO7YReUpG/i4ao3RyGTDF10Mejqpfe9BIcSY7wCzvihixa96v5TywCmNdE1hhqMYGsy7r8V5H7YQv8GSy2DV/K4rE7VGBHtCXnSBtxbIbjSGpxzp4kmOgV8gkgwnlFGludgNx0l4SEssYTIPrb5IONQmI1OsemCg1Em+zXYdUZ8GEOHLB/EKbd2DSiKu1ibzjxNemkdI6CNWNgh9JJ2h5J58mBh9ptYQBHPcVKTex1P8uXQ5/TVcbzyscHgQnxcKNb9MTz3iPspHVHFpAZqaC2EzC0Vj4JFTEAGfmCAZhvqSpYHw1JssxOJDXGaUPmK15nyz8whzkq9Y3ZjxpgJRpdurKp/clx8d0pN0NLq1vDYwGFsNqlLO8HGur4vyCnpOztG6k5ce1khgPKColHhR5jkQdz058NDFabOJTSWvjQdgfLfseTP6O7hBbEx69kCvZliyZq2UQ80WWxx18WGZdkNWH5JspVX42TT7+nqIDyyb+WlevoKrsxhqiaiyd4Q3TRs1V80D+wXRppsbGMZG1OcrV5Lz58ES+3pGFsHKfrCWvv+p/pNadeh96RTZAPgVlxMtjajsly1/Ks6/Jc+UqaBopNUVfe2Ndp+r0ihQcayTP0lJP99RZMBvsoKx34tY6DJv9UNC2oRyPfLbqVKG/JLu2q/7OO8WM2nF3SRu9eGtansqTgV3ksuBLzhKm8cr2QmrHkXgK5Ag+DilJTDpV1OBM7BKWYx02YsdAr/p34WS/+Q7rBX7pDp0z4bC7wi8IPrHtrspmr6JR8ttGgUnPtLaLfdhu5XFxw7fTQT85opPfwp23XQbWBD22kOmtnGSrXchAcEvs4lGbfL7klnWj2ne76uO/ZbFQNPBGjReZzpNr5G89ob/6FUWKIeN27pgAyq0BBaho8qJLs+EdZBGuS+AToSX2WWUTHJ25djGNY5fxj2kcNSxFCO81DvleEXV4KQthmL70wDJhAKv0+t6zLzeftghrBpeUTF6oiMKqin6lPF7soZRceeCHSID0N6fnFgUl7j7osvBVRi5e6Cbb6f6oZM2++5gA62qfA9uZyZTaJtRJixh2pntfODXhKrEqCvFL/lz1oAjuKycklHyrPlJsSbPVfaGRpor4eLZfk44SSna3DB/JdWqSP/v2426P19PJMPc2y6Agk1cgja0sLynLxHzgiOk4a6Bn4rl4zm7Ib4tQ+VpXQYmpyGHp5kRkuHsiZs98nFMublH4kBexDw84KnDX8ZlmXgZxD6rGoX1D7lQc23Gpr6esZlwceKoweGmersgVyAJEyHq6ePP0l0q8X+sxhfViX6izLBgQOrYo5mrvwBZg0mQpnaOFgouJ0ixoiCviw2I8eDRzw7IwW9QDdzfe7R+ebDWykpuJ2P3dKTEzh3TMdtBAHzFnHXBT2X3yR+2SKzH0LK1faUHzVVgY3RVVW/exQyWEY8d6JIy2i0FBNXqfn8mt4lXV6sXZCmIF2zV0uuJ/01cdQUqvV5YEiHou+Ij3Lqgkv11V0PbONNpN8XJiC4RkWTCBi0G+8qV8OP4n+l5UURs6eo/EaBNrfaNzb7owEmADgNUgAVyabOF+aD+iR7MzeExKzXLsflgyVXLfSml8CXA5WoeYmZcmeoo8e+gLFkU0Q+dCgJ12zf32OD1wb4ORM80vIZL8Etg4nPhtSK4rn+l5KqkjiANgfAnO2baTTRF3MEJ75FGG3HZraZhSRsTxMk9361bzM8wo5tmDucTflpFho4h9GjxOH/BzX6tmSLOZxgwynBkde/AVzth6FRg1oCM8YmEDZOLnYxlOg2NM2a0pBg0SjipCsfi2PsP6INtvNxhP7Y2gzq8iYmuQiNpD1VozbmB0LUnd6AZ0vPvlWVLcDD+sHVPdqH0ej4FkEObscMlI6nzH+IEgKZnktiNZQKsKlAEEQbJuzhA+hJYgLF0sNvREYuhUaUx1qzBpie++ImpZEzZ0F6m0W7k+b8Uj9KE9Zt4+69EvzidfNkc9mFvAHjcbUaFZu/jBFiPp6drYePZVRBahcKtlFJ82n5ktcCOtCyfT/XrwYqoAY79hXUvgoU0nfFVz+ZAMSS0NdkKtbpOxY6xnZPxfWIE4dLSqa8vu14hMFOQOi4bZS3aUqQg7+4nIlhSaO9CGwEBIJzi/1iNcM27vmw7jl3U/ji0h9eQ/WxMWxzJ3xGsVRG3oiQecGod/XNcL9mRQ+PEdPoNHaHh1cufuhtKLTje/DeSpJ4Wx11XdXcyyqVGh8JVHt4lYWKwaoGkO6r3S22PHaTLDGI81r1ECfhixAjbAGVLo7GnJlSX7v19V5ExNkbAQDKJgxcQnkbi4+WalUj7xqaRBIswcF7iUrCgz8n1MzED9rcwDZicMjpAgKECuE3zOy+tZNZNX3dr12vioAc/2t1p7p9o+LQxi1HmksInQl/aDESmhmx9hk/UuP32uquejC56MkYWF7aU79B6w8h3JJl+6Zv7fT8+H7j4QxE2FvLqIyDy4Uh/U0a/3AG/4L1SQfOuFamZWL5Rhn69LSBDl5Hnx4ytKihkiul49Wf3i1/VG+VkGCObAmakIOj1avoAXHGArkRRfy8EtWi5zzus2fSl3ZkHVxfekeOO3pUO0Msp9meizuXsFz3EwZX6lxRv1IeJOUk2aydS5ErwnPBTVzLW8dNUEPY269s/QrJV3PIKY3CFyKIqCvMyo+wihuXBqVvohHi1pxRB6f64z1JZIXpB696li83VzG0R2L42LjULLZDoljHMdGn154ENqhmSvY/TlrOvM/RwcT9pnBQz84cfOOBkkRKksAORjbQWGDEEXUIY7UEGERQQSHNvCpoIw164+jRuPQKYrW8qNiKJu2ZgGEAbuFPqFezNQ/U3vQaz3L4J3Gx62soBkakrTFBvGUiHpu5RK0pKGgNPa2B1KTmL6atdOjpVqlovtDdKIvT+5jzWVYfqzL+bV0dFXP4gm7TY43tPq0QlRuQoItbniPCihNs3chikhRf87YdYLpQJyNvxEdDSM5e7VLU/K6VXOKE224tjoUe6WZCAby2KJkiOsOJQhsavZqz/YmUobVhOqsDGzlXslbpEtNDwKBr/saubmEnCXyWOxv8P0KDmgKLrp+8b3ww2tEkDG113xfvNLq6+0vMFk/UFAL4gJXmmMTSootusNx743Zlf2GZkc9is6FUggPB9OoFYA7XGKck7/Pi/ofcNHBV0F6dKUlSnPRXoJ/xRSyl8EC060PMhrvOMhQxb56xgfmyMW9AM9Z5pgU2YSlNZQQWnNZD/bcabAs4XkGepboiKht7pD2tGY6Ze0RIdkmqEq4wFJfoluudK1zP4rslDdBXbxFtANidEUl6u7H6ndVm7jvUWdhLehgbPZ6vKdGciMURX1LKm10PCc9URgeJayElCLclDpQ22Tnn2GNAwQ2+E0g3uZr77Q7gALVO02H/2UcnxmCxrpgJuBziTXNyxDdEw5ENheGCETUSisjxb3A4wibCW13NR/00lKeNuWvrEVIrmeW0jJB1wLHTUAR/Fmi6CY8DjdJ4sVAA5wJqmxq3LYZzCS6zTRty/N/6xqUmieyT6om8XMXHiRuEU83yAV//hl6vNYBcejbPTBnRjc+flCzzuwYma1YxWIQvSXL+HPYFnahoFREMQnAnwc1lJnEHPlAcwhI3JKqNmPSOg18b0wTaDt2BiKHXJRMI3gSO1tlFjS7j0D0wf7yuf1v5lCBx8thT9EYRqO3LzfayD4zH4LT8WTHpGlp4gawQbBYmlYshc4omlpew8itmrQioZINqL5iLRblKOcFrit4p7Yb08ct84/3nyKknQ7adD4O1J4e39ChY33fuVE1MbqwUG1YqNuZs6T3aa23jq15Mk1YaJcezzxgr6k6681aAhat4z+qGNg/6FgFdt/0cJ6tKyQbKQ9RVnXPzkinU02vcLFjDWATI7d71Znon2a0LBN4tQH15yOffoKULsPWl6iKuwzjmBNMfE40f378k8c5WBeK2nhzt1XUyqKmyBlnbRVgci/p9nPcEGf/m19XWMYMuMKl3qTFIoA2Nr7RqdRzFmMhn+mkMvBnnTC4E5PfXzw0nSFeubq7J0IrPPKLHMlDJyKShO6wGV8UdV0rg8rsG+Y3PYzi/6UTQMVrRNhUczv1vYgkBBKng4+apwYDxDEw0St0OhgX3i1NWrMwEj5vMWGOWAg+3Cp51+aAHkYUl7eZD/jRp4Cc6undrB/jmfwRtE9/pzH2nxnck0V2J43Xh1p20y9KpIPxFLpzGXEaevTIM1YM7f1pfuCtFX+IWveqtUkOnx1aWPpa7cQGASRG97U3ahzkYLIaTf2XNKbK9s8COX4vLZW2TkdtoRI2l9yfGsSAF17ul+jw2f9EWq0sYiZJyOf/1kq5ncxsii+8hrJPUMh64DWDy0nQm5C2fedFCJwTH1MQLqX9Vodj97GKmaTSimrakNeHHH/P30dMu9MlOvmyFlodFnJe9MG0zVvvNoWlFN02qRmzV7RdNuQ9KPhefQyC7PSd4fA0SiXWVkp8nHT7FzaSe6yHwp+pkKLtwLz9Fx82HyMAye/aAlZa/EFpoeZ24942fncHvzxVkeVmgIljPrHH3qqh9sYLRGkCdCeJ+6UJUy8I0buUELJO17vSxG8R8SkFJCvnyeXKMfjz5vnAarJ6+b/Bp96FqgxvOKk32finXM8RblrAcgebqBsoRKZ3lLK78oVPOXySwyDcGSpvCDmOAiGPq7L6e40sKurHdELKXXdXLimsXfHtQkBoIZJSLLgD9fjknorSgD3twmwYuvjhaWR+LN392KU652KTqLyLbWhP+NrJ3HFgS7oKGIu9Dwm26wDxKkvjTXBe92RPxHHvZ6kVGsqT9pvTfkEjlUYYnAigUgM0LzlBSDrtzgJKUBDYhH68EPziPpmaCQ838qS9Sq600CElXjcYGUcyLexh4Xv44If1ebglQvwC699VIlY9DPqnhrHviPcGZbBjGHnb/fs0BfzwJwa04wdFJufSxUaobh8JpdXLtwIQ53W5LjJFTxyBe/RVDserzEdDbPl5B2gRqQlgbgBwleoXkGxp5nSupQqkbtKPGOeO/4SfdRQPnpD1pzNNw0cRuHfz57DYCVGD+unV6efA9+IAY7nXrz62IaieveCQOwFwefbVSYySF+YhET+3f4xaEGHgjfqJ86BtZXGasefbup3QNOuJzT7AmTN4Wmg78JYlYSCPTQkh2K3f9EsQbFiDwB7D84NQIK3p2aX5dekvn0bjERcfCv2gYLvLJyrosNkNE5ylVV6TLM0Fu+X0PzxwKrBNS785ddeDG7qm6sQXJcxDd+ZJeZ3TnL1qRCcQg1dW6t1fADcBVpIOPYsZZ/coffJ6an7Y+YyhM9e2lVuCyMEkA9UxKZk/AcwmQbgddmkvbu/C8BHZ8JcjaU7Z3Zcyx79hg9C5HFBiNw5L1A5moKv4cetoAcPLocck67jgdJQ9JKxVvb3m3l+xZKIYUNXsFUVjQqxDPeyHk7pmByz2VwVRe6kPAeIHl0WwqEI/bN5RuEYhnhnsylKz4DHdMEzeDAZTY5PlldObsrwfvhLfiHYMkV4JYcqcNvFJV4lfXObdDuqAZ1Vw5R8rgjhZm438ucr9ICvrDu8R+rw1XiexoRbAs04XPdHAYloJYt/tp0kOL1bOCqJ8BXhcdRihsZmdKdwyabjUf23jc7Kpzao1Lv7PbjmgU4FC8eGRUEBS1sXTTMYNshLixIUa5t+8D0R/gFJOo2Nlf4YYUBiDKNi+hRwlfdgdR3PfPwFwqfL4PmWWnFCJ8CqwA9DOdWD73XE3e6oj9GrmskocOON3wXy7TTEyWPIFfxm1adnvSsSLOxdR39e85VunQ==,iv:u5bfjSgvZbWjPTLLZVEc3cvZKlRKpaJlqFpo2hOKNsA=,tag:vcIlC2VyjIx+bV5RbNWgYA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S0R5dHBTdmdZdUhXNXY0
        NXlXQTJoRU9FOTJURm9EOVRnVGpITmpQVUdnCjBGWTBiM1pqcWthMFR0bjkzTTRa
        WFVTcG9oWjRZRjgxOWw0TGVyWjBBTmsKLS0tIDhJTThxeUl4ZkxaOWpVMDFQN0p6
        WGNzOWRncDVuM0dLNlgvNURtZmNLWW8Kocettlm8KH2uqj1ndKMj8VhSQ+EhVjbp
        How3q+w0RyAFq2BtwdId0a4b/VxPGujjd2hKr1KI6nxFfDtVguIqYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T18:28:02Z"
  mac: ENC[AES256_GCM,data:bGJeO3ZY39AEsbWgTg3N9VA4pOgNJYFgWX+MiHAAM4tJT4GpGyn3ATw8q/XGNcBCAVy3w1V1Dt+/vW+8z2M2ss4P8UX8KbaelWTobVYQI0XP4QxugXjHxs26juABFqcDr902MHYrCmHlAqex9PuR7EvZojJiBv0gvj0uvvFWNtE=,iv:S6NKV+eqyWwW8ffY/BDWoi4Fz1PersvM/FyiyCRSlDo=,tag:StNnHclFZszaQp1eBGHy9g==,type:str]
  pgp: []
  encrypted_regex: ^(GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|rootPassword)$
  version: 3.9.1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meowlnir
  namespace: matrix
spec:
  replicas: 0
  selector:
    matchLabels:
      app: meowlnir
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meowlnir
    spec:
      containers:
        - image: dock.mau.dev/maunium/meowlnir:v0.4.0
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/meowlnir
          args:
            - --no-update
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /_matrix/mau/live
              port: 29339
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: meowlnir-container
          resources:
            requests:
              ephemeral-storage: 1024Mi
              cpu: 100m
              memory: 200Mi
            limits:
              ephemeral-storage: 2048Mi
              cpu: 2000m
              memory: 2000Mi
          ports:
            - containerPort: 29339
          readinessProbe:
            httpGet:
              path: /_matrix/mau/ready
              port: 29339
            initialDelaySeconds: 30
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            #runAsNonRoot: true
          volumeMounts:
            - mountPath: /data/config.yaml
              name: meowlnir-config
              subPath: config.yaml
              readOnly: true
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: meowlnir-config
          secret:
            secretName: ENC[AES256_GCM,data:XskgREuZE9Y=,iv:tMM4u3Y+Bo5TpjfXEaag354aPpPC1kaqSRREzhtWXU8=,tag:uApSuO4jExZ888/IEqWoQA==,type:str]
        - name: tmp
          emptyDir:
            sizeLimit: 2048Mi
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S0R5dHBTdmdZdUhXNXY0
        NXlXQTJoRU9FOTJURm9EOVRnVGpITmpQVUdnCjBGWTBiM1pqcWthMFR0bjkzTTRa
        WFVTcG9oWjRZRjgxOWw0TGVyWjBBTmsKLS0tIDhJTThxeUl4ZkxaOWpVMDFQN0p6
        WGNzOWRncDVuM0dLNlgvNURtZmNLWW8Kocettlm8KH2uqj1ndKMj8VhSQ+EhVjbp
        How3q+w0RyAFq2BtwdId0a4b/VxPGujjd2hKr1KI6nxFfDtVguIqYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T18:28:02Z"
  mac: ENC[AES256_GCM,data:bGJeO3ZY39AEsbWgTg3N9VA4pOgNJYFgWX+MiHAAM4tJT4GpGyn3ATw8q/XGNcBCAVy3w1V1Dt+/vW+8z2M2ss4P8UX8KbaelWTobVYQI0XP4QxugXjHxs26juABFqcDr902MHYrCmHlAqex9PuR7EvZojJiBv0gvj0uvvFWNtE=,iv:S6NKV+eqyWwW8ffY/BDWoi4Fz1PersvM/FyiyCRSlDo=,tag:StNnHclFZszaQp1eBGHy9g==,type:str]
  pgp: []
  encrypted_regex: ^(GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|rootPassword)$
  version: 3.9.1
---
apiVersion: v1
kind: Service
metadata:
  name: meowlnir
spec:
  selector:
    app: meowlnir
  ports:
    - port: 29339
      targetPort: 29339
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3S0R5dHBTdmdZdUhXNXY0
        NXlXQTJoRU9FOTJURm9EOVRnVGpITmpQVUdnCjBGWTBiM1pqcWthMFR0bjkzTTRa
        WFVTcG9oWjRZRjgxOWw0TGVyWjBBTmsKLS0tIDhJTThxeUl4ZkxaOWpVMDFQN0p6
        WGNzOWRncDVuM0dLNlgvNURtZmNLWW8Kocettlm8KH2uqj1ndKMj8VhSQ+EhVjbp
        How3q+w0RyAFq2BtwdId0a4b/VxPGujjd2hKr1KI6nxFfDtVguIqYw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T18:28:02Z"
  mac: ENC[AES256_GCM,data:bGJeO3ZY39AEsbWgTg3N9VA4pOgNJYFgWX+MiHAAM4tJT4GpGyn3ATw8q/XGNcBCAVy3w1V1Dt+/vW+8z2M2ss4P8UX8KbaelWTobVYQI0XP4QxugXjHxs26juABFqcDr902MHYrCmHlAqex9PuR7EvZojJiBv0gvj0uvvFWNtE=,iv:S6NKV+eqyWwW8ffY/BDWoi4Fz1PersvM/FyiyCRSlDo=,tag:StNnHclFZszaQp1eBGHy9g==,type:str]
  pgp: []
  encrypted_regex: ^(GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|rootPassword)$
  version: 3.9.1
