apiVersion: v1
kind: ConfigMap
metadata:
    name: persephone-config
    namespace: persephone
data:
    config.yaml: ENC[AES256_GCM,data:OAxftLR0pT6nPfTTEPkrU3xPYSqX7g720eTdcclpFH5gsGeh+bN8dJ71q75dInuu1N/A3aLdvjF4UbIiPiV48XfpWw+WI0asxtoOjUx+6enUMxFQ+gT6Ny6E09x+sZhjre9z1HD1PckQxHwg7FLAlP5Pdyk7AsP8B9cynonk0trkXllaHzfKHcPqaCofaftUXG28arc0t195OEit1feZy6rPNIBoyZ2DS8Ai3aUP9E1Mvq1tG5xoxz8zIBKaFeVpHNq9uT0an5yP3QThqmRrzpCifFXjXCoqS4CABc2ct43DMuGW+Kkvxr0Idmnh/jsI6vF+3uIuwsGFYQPokIl7ncOru9ZklyMx3rml6zUJbjF7Bpn0a/gh/M4/oQ6nM03+mozuFuhv8reE2i3yH+7JZxY4qOBmj1b21uRngji1yVxLW3Yt0Jby16eCe4HdkgeYiekpPRE9QkbqQbfxBI1YHGwtCPdh8NQsZSSDhQ==,iv:ibKYs4CMvYpgU6NZGah3P7IdKxX2Jjeri8VX5vAMk/Q=,tag:jBrEbKly4weK/ysnUg7vHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcEVJd2hjeHhUZ1FPQ3hv
            U0ZLM282UmRNZ0pKMDVXWkxFcUtrSWhYRzFNCmxTTEc0czBMTDEzemVhcW4vbDZz
            VzB4ejRnMGIxTWZseWpTK1ZmTHluQW8KLS0tIHdpU3NRbEx4UzNTcjVjQmlTL0Vy
            YmVzbCtXbXNsdW5mdEFPMDFWcWRIM2MKmV7ExXjtoY3LQLpD2nxLB5c5PbiBeguP
            XynhU2EHTQDpVDI60KN7bdEbxHp6uuAYOvCvYkq8KAM1r0gaS2nrrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T19:04:20Z"
    mac: ENC[AES256_GCM,data:kiQhNJGY6geKXWKrumAV3lfw0GtI+OmRueYc/v7cShMIxKTjQ2v7WaQYzIkgUpyyM/0nrIBgRy3euDQOjuVCqMQRHdNPJ1ju+Kg/J0way2ETa80o9vJJjn6Wfc+Nnm/88//TDACpwxmcgdfmvDTlEQmVjTp/z30hqv2GS6l83Ww=,iv:qaxB7Me8LuIKbTW73376RmTp7FnYV29sB/n6BCVV0fw=,tag:tgfgcuxNQkjAv8/G0Zyw+w==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
