apiVersion: v1
kind: ConfigMap
metadata:
    name: persephone-config
    namespace: persephone
data:
    config.yaml: ENC[AES256_GCM,data:5w/0W1KcvvrmSFl/YGJdeUULGMlV9o/PRAbefq3xU8aauyj6rYWLYb6QDO9wMzsHf7N8OvPi4f4vM5gncK4QOyP7vIKaP+JPbM9/cFm/JvGtPE0JIEJDwV7Rzp3kGHVB5QCxm8Od0tji7PHBmEGLmWwu6z82elqsb8nmdGdXnbiIswWJngLE7zeXnZ33muoyfOzIe6l3yWXpbKrzNEYWcXp/De2CpKPcEXG4Wb2nNnPoJS1MDBYBM+a9SHXX/xsmMhlg5GjWvScfSnHeIDj5w7x9PXJYPlvGUROjDRLNt50icKZvdcNcN88oM4mQFVUad5iFBy5ndOF5I3K/zRjEu/49PtSME4BnBdiWlQJ2SmlwnoCsDnPGTcql8DTVYyjsQuG6EAIliTBfBHDeLdWoElSmpJh9Uimx7GJGmFF124c27ENTJRcx8x+i3Ntr2E+JLD80+HlrgJoshkiN+ysBWFChHvhRN1SC+R+e,iv:4YIXfOwf2BWGRKBfzJCae+bFtjAn3J148wxFL1c/WxM=,tag:ex7t8lAFWVLknprexF6ofw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1esjyg2qfy49awv0ptkzvpk425adczjr38m37w2mmcahzc4p8n54sll2nzh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeS9wQ3BBYzBVeXNBcTZi
            OWo4RGYzVWUrSzlzdDdqUkkxN1dVZUJqdnhvCk9MeDNKbi9UT2NpQ1lCbG43dThq
            Q3JXdzBhZTlkd2I5SGNkMVYzRFlTOGsKLS0tIDg5QTJaYnNoc3VNQWlOWmx2NGc3
            MGIvSHlvTFVVSENjb081TjlZRWJUQW8KR5mf66KE4+UevIYpXYaVSMlf4/OiaM/X
            1CxdIpxml5qiM0y+WTc6nfrlxcyG9Ke56taHTQaKvvQ6RBp439Bccg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-09T18:59:36Z"
    mac: ENC[AES256_GCM,data:kpPIisIKIPk1M6EhalYv04NBGqjI5cZdOq/dS/+/GR2U3GIqWpne5ITsIwtkjD1989o2xsJKy/HGVJgE7/0FWj5u+ZBSaPMFZiLzp8fjXBup9GUBGGPF7UzYUB6JxHb6PZ4eRmXd/Ne7jx7g5nKcAW37QSSBwsOSpPjbZ2+HfQ8=,iv:vLHXXes7Q6SuzvjWb94XLueBi7CMtllvtpBuX+Gz9pM=,tag:zRFbL7/efCCxB4iOWMjxOw==,type:str]
    pgp: []
    encrypted_regex: ^(apiKey|appUserPassword|otelUserPassword|harborAdminPassword|totpVaultKey|kimaiAppSecret|kimaiAdminPassword|GITHUB_CLIENT_ID|GITHUB_CLIENT_SECRET|GITHUB_PRIVATE_KEY|woosh|root_password|rspamd_password|pgdb_password|matrix_access_token|pgdb_remote_url|hmac_secret_key|adminPassword|adminEmail|jenkinsAdminEmail|securityRealm|gerrit.config|routing_key|DATABASE_URL|SMTP_PASSWORD|SECRET_KEY_BASE|admin_password|extraCommands|key|clickhouseDatabaseURL|databaseURL|client_id|client_secret|secret_key_base|otp_secret|private_key|public_key|primaryKey|deterministicKey|keyDerivationSalt|token|clientId|secretKey|installationId|installationKey|uriOverride|adminToken.value|password.value|sql_password|erlangCookie|AUTHENTICATION_PASSWORD|ROOM_API_SECRET_KEY|adminPassword|configPassword|adminUser|configUser|MAIL_PASSWORD|APP_KEY|api_key|api_secret|keys|livekit_key|livekit_secret|secret_key|admin_pass|admin_email|mariadbPassword|mariadbRootPassword|privateKey|data|stringData|PASSWD|password|pass|postgresPassword|postgresqlPassword|redminePassword|smtpPassword|registration_shared_secret|shared_secret|secret|admin_token|integrationKey|rootPassword|adminPassword|adminUser|adminEmail|emailPassword|secretKey|appId|clientSecret|webhookSecret)$
    version: 3.9.1
