apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-updater.yaml
  - descheduler.yaml
  - capacitor.yaml
  - ./cloudnative-pg-operator
  - cert-manager.yaml
  - cilium.yaml
  - longhorn.yaml
  - ./velero
