apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - repository.yaml
  - release.yaml
  - route.yaml
secretGenerator:
  - name: immich-database
    # Prevent the name from changing on each kustomize build
    options:
      disableNameSuffixHash: true
    files:
      - database-credentials.properties
