apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./dashboards
  - pg_dashboard_configmap.yaml
  - repository.yaml
  - longhorn-storageclass.yaml
  - prometheus-release.yaml
  - thanos-release.yaml
  - thanos-secret.yaml
  - minio_loki_metrics.yaml
  - prometheus-adapter.yaml
  - scrape-dns.yaml
  - external-costs.yaml
