apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-tester
  namespace: matrix
spec:
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: connectivity-tester
  template:
    metadata:
      labels:
        app: connectivity-tester
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - connectivity-tester
              topologyKey: "kubernetes.io/hostname"
      hostNetwork: false
      containers:
        - name: connection-checker-ui
          image: ghcr.io/mtrnord/matrix-connection-tester-ui:v0.3.1
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                  - sleep
                  - "10"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
            - containerPort: 8000
              name: web
              protocol: TCP
          volumeMounts:
            - name: configs
              mountPath: "/app/_fresh/client/config.json"
              subPath: config.json
              readOnly: true
            - mountPath: /tmp
              name: tmp
          livenessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /
              port: web
              scheme: HTTP
          startupProbe:
            httpGet:
              path: /
              port: web
      volumes:
        - name: configs
          configMap:
            name: connectivity-tester-config
        - name: tmp
          emptyDir:
            sizeLimit: 2048Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectivity-tester-api
  namespace: matrix
spec:
  progressDeadlineSeconds: 120
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: connectivity-tester-api
  template:
    metadata:
      labels:
        app: connectivity-tester-api
    spec:
      automountServiceAccountToken: false
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - connectivity-tester-api
              topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: federation-tester-api
          image: ghcr.io/mtrnord/rust-federation-tester:0.3.2
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              memory: "344Mi"
              cpu: "252m"
          volumeMounts:
            - name: api-config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          ports:
            - containerPort: 8080
              name: api
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: api
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: api
              scheme: HTTP
          startupProbe:
            httpGet:
              path: /healthz
              port: api
          env:
            - name: RUST_LOG
              value: rust_federation_tester=info,hyper=warn,sea_orm=info,tower_http=debug
      volumes:
        - name: api-config
          secret:
            secretName: connectivity-tester-config
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: connectivity-tester-latency
  namespace: matrix
spec:
  provider:
    type: prometheus
    address: "http://vmselect-vm-victoria-metrics-k8s-stack.monitoring.svc:8481/select/0/prometheus"
  query: |
    histogram_quantile(0.99,
      sum(
        irate(
          envoy_cluster_upstream_rq_time_bucket{
            envoy_cluster_name=~".*{{ namespace }}/{{ target }}.*",
          }[{{ interval }}]
        )
      ) by (le)
    )/1000
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: connectivity-tester-error-rate
  namespace: matrix
spec:
  provider:
    type: prometheus
    address: "http://vmselect-vm-victoria-metrics-k8s-stack.monitoring.svc:8481/select/0/prometheus"
  query: |
    sum(
      rate(
        envoy_cluster_upstream_rq{
          envoy_cluster_name=~".*{{ namespace }}/{{ target }}.*",
          envoy_response_code!~"5.*"
        }[{{ interval }}]
      )
    )
    /
    sum(
      rate(
        envoy_cluster_upstream_rq_total{
          envoy_cluster_name=~".*{{ namespace }}/{{ target }}.*",
        }[{{ interval }}]
      )
    ) / 100
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: connectivity-tester
  namespace: matrix
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connectivity-tester
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  #autoscalerRef:
  #    apiVersion: autoscaling/v2
  #    kind: HorizontalPodAutoscaler
  #    name: connectivity-tester
  service:
    # service port number
    port: 8000
    # container port number or name (optional)
    targetPort: 8000
    # Gateway API HTTPRoute host names
    hosts:
      - connectivity-tester.mtrnord.blog
      - federationtester.mtrnord.blog
    # Reference to the Gateway that the generated HTTPRoute would attach to.
    gatewayRefs:
      - name: envoy-gateway
        namespace: envoy-gateway
    retries:
      attempts: 10
      perTryTimeout: 5s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
      - name: error-rate
        # max error rate (5xx responses)
        # percentage (0-100)
        templateRef:
          name: connectivity-tester-error-rate
          namespace: matrix
        thresholdRange:
          max: 2
        interval: 1m
      - name: latency
        templateRef:
          name: connectivity-tester-latency
          namespace: matrix
        # seconds
        thresholdRange:
          max: 3
        interval: 30s
    sessionAffinity:
      cookieName: flagger-cookie
    # testing (optional)
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -s http://connectivity-tester-canary.matrix:8000"
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 10m
        metadata:
          cmd: "hey -z 10m -q 10 -c 2 http://connectivity-tester-canary.matrix/?serverName=mtrnord.blog"
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: connectivity-tester-api
  namespace: matrix
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: connectivity-tester-api
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  #autoscalerRef:
  #    apiVersion: autoscaling/v2
  #    kind: HorizontalPodAutoscaler
  #    name: connectivity-tester
  service:
    # service port number
    port: 8080
    # container port number or name (optional)
    targetPort: 8080
    # Gateway API HTTPRoute host names
    hosts:
      - api.connectivity-tester.mtrnord.blog
    # Reference to the Gateway that the generated HTTPRoute would attach to.
    gatewayRefs:
      - name: envoy-gateway
        namespace: envoy-gateway
    retries:
      attempts: 10
      perTryTimeout: 5s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
      - name: error-rate
        # max error rate (5xx responses)
        # percentage (0-100)
        templateRef:
          name: connectivity-tester-error-rate
          namespace: matrix
        thresholdRange:
          max: 2
        interval: 1m
      - name: latency
        templateRef:
          name: connectivity-tester-latency
          namespace: matrix
        # seconds
        thresholdRange:
          max: 1
        interval: 30s
    sessionAffinity:
      cookieName: flagger-cookie
    # testing (optional)
    webhooks:
      - name: smoke-test
        type: pre-rollout
        url: http://flagger-loadtester.flagger-system/
        timeout: 15s
        metadata:
          type: bash
          cmd: "curl -s http://connectivity-tester-api-canary.matrix:8080/healthz | grep 'ok'"
      - name: load-test
        url: http://flagger-loadtester.flagger-system/
        timeout: 10m
        metadata:
          cmd: "hey -z 10m -q 10 -c 2 http://connectivity-tester-api-canary.matrix/api/federation/federation-ok?serverName=mtrnord.blog&no_cache=true"
