apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - envoy.yaml
  - monitoring.yaml
  - authentik.yaml
  - matrix.yaml
  - vaultwarden.yaml
  - actualbudget-server.yaml
  - collabora.yaml
  - flagger.yaml
  - gotosocial.yaml
  - continuwuity.yaml
  - freshrss.yaml
  - ntfy.yaml
  - mailserver.yaml
  - plane.yaml
  - kimai.yaml
  - statistics.yaml
  - harbor.yaml
  - cgit.yaml
  - blog.yaml
  - bookwyrm.yaml
  - neoboard.yaml
  - ci.yaml
  - weblate.yaml
  - sentry.yaml
