apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: matrix
resources:
  - draupnir-appservice-secret.yaml
  - draupnir4all-web.yaml
  - deployment.yaml
  - service.yaml
  - metrics.yaml
