apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pdns-secret.yaml
  - cluster-issuers.yaml
  - pg-secrets.yaml
  - cnpg-cluster-barmancloud-ext.yaml
  - cnpg-base.yaml
  - cnpg-cluster.yaml
  - velero-schedules.yaml
