apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickstack
resources:
  - repository.yaml
  - release.yaml
  - route.yaml
  - secrets.yaml
  - k8s_log_metrics_collector.yaml
  - k8s_events_global_metrics_collector.yaml
