apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoy-gateway
  - ./monitoring-stack
  - ./externaldns
  - ./authentik
  - ./draupnir4all
  - ./draupnir-synapse
  - ./vaultwarden
  - ./actualbudget-server
  - ./collabora
  - ./flagger
  - ./gotosocial
  - ./connectivity-tester
  - ./continuwuity
  - ./freshrss
  - ./ntfy
  - ./mailserver
  - ./plane
  - ./kimai
  - ./wkd
  - ./cgit
  - ./blog
  - ./plausible
  #    - ./matrix-org-statistics
  - ./bookwyrm
  - ./miro-neoboard-exporter
  #- ./concourse
  - ./weblate
  #- ./sentry
  - ./immich
